seed_everything: 35
default_dtype: float32

# `execution_mode` and `restore_checkpoint` control how the training is executed.
# - `train`: Use this to train from scratch or resume training.
#   - If `restore_checkpoint` is null, it trains from scratch.
#   - Otherwise, it resumes training from the checkpoint by `restore_checkpoint`.
# - `finetune`: Use this to finetune a model from a checkpoint; of course, a
#   `restore_checkpoint` must be provided in this case. The code only restores model 
#   parameters from the checkpoint and will use values specified in the config file
#   for all other hyperparameters.
execution_mode: train # options are `train` and `finetune`
restore_checkpoint: null # path to checkpoint file

data:

  trainset_filename: /Users/mjwen/Documents/Research/Dataset/matpes/matpes_n20.json
  valset_filename: /Users/mjwen/Documents/Research/Dataset/matpes/matpes_n20.json
  testset_filename: /Users/mjwen/Documents/Research/Dataset/matpes/matpes_n20.json
  target_names:
    - energy
    - forces
    - stress

#  trainset_filename: /Users/mjwen/Documents/Research/Dataset/UNEP-v1/unep-v1_n20.json
#  valset_filename: /Users/mjwen/Documents/Research/Dataset/UNEP-v1/unep-v1_n20.json
#  testset_filename: /Users/mjwen/Documents/Research/Dataset/UNEP-v1/unep-v1_n20.json
#  target_names:
#    - energy
#    - forces
#    - stress

#  trainset_filename: /Users/mjwen/Documents/Research/Dataset/mad/mad_n20.json
#  valset_filename: /Users/mjwen/Documents/Research/Dataset/mad/mad_n20.json
#  testset_filename: /Users/mjwen/Documents/Research/Dataset/mad/mad_n20.json
#  target_names:
#    - energy
#    - forces

#  trainset_filename: /Users/mjwen/Documents/Research/Dataset/mace-off23/251125/mace-off23_n20.json
#  valset_filename: /Users/mjwen/Documents/Research/Dataset/mace-off23/251125/mace-off23_n20.json
#  testset_filename: /Users/mjwen/Documents/Research/Dataset/mace-off23/251125/mace-off23_n20.json
#  target_names:
#    - energy
#    - forces

  r_cut: 5.0
  train_batch_size: 4
  val_batch_size: 20
  test_batch_size: 20

model:
  # General
  # `tp_path_mode` and `tp_path_polar_only` control the way to select the paths for
  # tensor product.
  # Options for `tp_path_mode` are: `full`, `lite`, `level`, and `camp`. See CarNet
  # manuscript for details.
  # If `tp_path_polar_only` is true, this further downselects paths that generate polar
  # tensors, whereas paths that generate axial tensors are discarded.
  # Note, `lite` or `camp` modes only generate polar tensors by construction, so when
  # they are used, `tp_path_polar_only` has no effect.
  tp_path_mode: lite
  tp_path_polar_only: false
  F: 8 # number of channels
  num_layers: 2 # number of layers
  num_average_neigh: auto # average number of neighbors (float), if `auto` determined automatically from training set

  # ZBL repulsion
  use_zbl: true # use ZBL potential for short-range repulsion
  zbl_trainable: true # Train ZBL parameters or not; ignored if `use_zbl` is `false`

  # angular
  max_L: 3 # max rank of natural tensor
  max_degree: 3 # max correlation degree

  # atomic energy shift and scale
  # Final energy = scale*e + shift + element_bias (if element_bias is True)
  # if `null`, not used
  # if `auto`, automatically determined from dataset
  atomic_energy_scale: auto
  atomic_energy_shift: /Users/mjwen/Documents/Research/Dataset/matpes/matpes_r2scan_atomic_energy.json
  element_bias: false
  # atomic_energy_shift: auto
  # element_bias: true

  # radial
  radial_mlp_hidden_layers: 2
  radial_basis_degree: 8
  radial_basis_type: bessel

  # optional layers
  use_linear_channel_input: false
  use_linear_channel_hyper: false
  residual: true
  use_linear_channel_residual: true # this is ignored if `residual` is `false`

  # How the weight is represented in eq. 6. Options are:
  # `independent`: weight does not depend on atomic species
  # `full`: a single weight W_FF'z is used, where z is atomic species
  # `factorized`: weight is factored as W_FF'z = W_FF'*Wz
  atomic_moment_weight_mode: independent # independent, full, factorized

  # How the weight is represented in eq. 8. Options are the same as above.
  # This is used only when `residual` is true and `use_linear_channel_residual` is true
  residual_weight_mode: factorized # independent, full, factorized

  # output
  output_mlp_hidden_layers: 2

loss:
  type: huber # options are `mse` `mae` and `huber`
  delta: 0.01 # Hubber delta, only used if type is `huber`
  energy_ratio: 1.0
  forces_ratio: 1.0
  # Carnet adopts the usual stress convention. And virial = - stress * volume.
  # Positive diagonal components of the stress tensor mean that the system is under
  # tension (and wants to compress), whereas negative ones mean that the system is
  # under compressive strain (and wants to expand).
  # But in some DFT codes (e.g., VASP), the opposite convention is used.
  #
  # If stress ratio is 0 or not set, stress is not used in training
  stress_ratio: 1.0
  normalize: true # normalize energy by number of atoms

metrics:
  type: mae
  normalize: true # normalize energy by number of atoms

ema: # exponential moving average, https://github.com/lucidrains/ema-pytorch
  beta: 0.999
  update_after_step: 1000
  update_every: 1
  power: 0.75
  include_online_model: false

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.002
    weight_decay: 1.0e-8

lr_scheduler:
  monitor: val_ema/mae_f
  class_path: torch.optim.lr_scheduler.ReduceLROnPlateau
  init_args:
    mode: min
    factor: 0.8
    patience: 100
#lr_scheduler:
#  class_path: torch.optim.lr_scheduler.CosineAnnealingLR
#  init_args:
#    T_max: 5 # should be equal to trainer.max_epochs

trainer:
  max_epochs: 2
  accelerator: cpu
  num_nodes: 1
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  detect_anomaly: false
  inference_mode: false # Enable calculation of gradients (forces) in val/test step
  gradient_clip_val: 100.0

  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      project: carnet_proj

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelSummary
      init_args:
        max_depth: -1
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: null
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_ema/mae_f
        mode: min
        save_top_k: 3
        verbose: false
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_ema/mae_f
        mode: min
        patience: 200
        verbose: true

wandb_base_url: https://api.bandw.top  # https://api.wandb-cn.top
