seed_everything: 35
default_dtype: float32
restore_checkpoint: null # path to checkpoint to restore from; if `null`, train from scratch

data:
  # name and signature of the target property
  # The target should be given as a dictionary, {rank: T}, where rank is the rank of
  # the natural tensor, and T is the values of the natural tensor. The shape of T
  # should be (1, number, 3**rank), where `number` gives the number of tensors of the
  # corresponding rank.
  #
  #  NOTE, in the dataset file, the tensor should be given with the name
  #  `[target_name]_[target_mode]`, e.g. `elastic_tensor_natural`
  target_name: dipole_moment_tensor
  target_mode: natural
  target_symmetry: i
  target_signature: # {rank: number} of the natural tensor
    1: 1
  trainset_filename: /Users/mjwen/Documents/Research/Projects/carnet_analysis/dataset/ethanol_tensor/20250730/ethanol_n20.json
  valset_filename: /Users/mjwen/Documents/Research/Projects/carnet_analysis/dataset/ethanol_tensor/20250730/ethanol_n20.json
  testset_filename: /Users/mjwen/Documents/Research/Projects/carnet_analysis/dataset/ethanol_tensor/20250730/ethanol_n20.json
  r_cut: 5.0
  train_batch_size: 8
  val_batch_size: 8
  test_batch_size: 8

model:
  # general
  tp_path_mode: full # options: `full`, `lite`, `camp`
  F: 8 # number of channels
  num_layers: 2 # number of layers
  num_average_neigh: auto # average number of neighbors (float), if `auto` determined automatically from training set

  # angular
  max_L: 2 # max rank of natural tensor
  max_degree: 3 # max correlation degree

  # radial
  radial_part_type: 1
  radial_mlp_hidden_layers: 2
  max_chebyshev_degree: 8 # max degree of Chebyshev polynomial for the radial part

  # optional layers
  use_linear_channel_input: false
  use_linear_channel_hyper: true
  use_linear_channel_residual: true
  use_atomic_dependent_weight: true
  residual: true

  # output
  output_mlp_hidden_layers: 2 # number of hidden layers in the output MLP for scalars
  output_from_all_layers: true
  target_shift: auto # shift dict {rank: tensor}. `auto` to determine it automatically from training set; `null` to not use it
  target_scale: auto # scale dict {rank: tensor}. `auto` to determine it automatically from training set; `null` to not use it
  use_layer_norm: true # use layer norm in the output head
  reduce: sum

loss:
  # ratio of the loss for each rank of natural tensor
  # The loss is: \sum w_i (y_i - \hat y_i)^2,
  # where y_i is the model prediction for natural tensor of rank i, and \hat y_i is corresponding target;
  # w_i is the weight for the loss of natural tensor of rank i.
  ratio:
    # dipole moment tensor
    1: 1.0

metrics:
  type: mae
  validation_start_epoch: 0 # start calculating metrics at this epoch, can be used to avoid nan in the first few epochs

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.002
    weight_decay: 1.0e-8

lr_scheduler:
  monitor: val_ema/mae_rank-1
  class_path: torch.optim.lr_scheduler.ReduceLROnPlateau
  init_args:
    mode: min
    factor: 0.8
    patience: 100
    verbose: true
#lr_scheduler:
#  class_path: torch.optim.lr_scheduler.CosineAnnealingLR
#  init_args:
#    T_max: 5 # should be equal to trainer.max_epochs

ema: # exponential moving average, https://github.com/lucidrains/ema-pytorch
  beta: 0.99
  update_after_step: 1000
  update_every: 10
  power: 0.75
  include_online_model: false

trainer:
  max_epochs: 2
  accelerator: cpu
  num_nodes: 1
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  detect_anomaly: false
  inference_mode: true
  gradient_clip_val: 100.0

  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      project: carnet_proj

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelSummary
      init_args:
        max_depth: -1
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: null
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_ema/mae_rank-1
        mode: min
        save_top_k: 3
        verbose: false
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_ema/mae_rank-1
        mode: min
        patience: 200
        verbose: true

wandb_base_url: https://api.bandw.top  # https://api.wandb-cn.top
