seed_everything: 35
default_dtype: float32
restore_checkpoint: null # path to checkpoint to restore from; if `null`, train from scratch

data:
  trainset_filename: /Users/mjwen/Packages/camp_analysis/dataset/nequip_LiPS/train_10_LiPS.json
  valset_filename: /Users/mjwen/Packages/camp_analysis/dataset/nequip_LiPS/train_10_LiPS.json
  testset_filename: /Users/mjwen/Packages/camp_analysis/dataset/nequip_LiPS/train_10_LiPS.json
  #
  #  trainset_filename: /Users/mjwen/Packages/carten_analysis/dataset/ethanol_tensor/ethanol_n20.json
  #  valset_filename: /Users/mjwen/Packages/carten_analysis/dataset/ethanol_tensor/ethanol_n20.json
  #  testset_filename: /Users/mjwen/Packages/carten_analysis/dataset/ethanol_tensor/ethanol_n20.json
  #
  #  trainset_filename: /Users/mjwen/Packages/carten_analysis/dataset/rmd17/20250702/json_data/rmd17_aspirin_val.json
  #  valset_filename: /Users/mjwen/Packages/carten_analysis/dataset/rmd17/20250702/json_data/rmd17_aspirin_val.json
  #  testset_filename: /Users/mjwen/Packages/carten_analysis/dataset/rmd17/20250702/json_data/rmd17_aspirin_val.json
  #
  #  trainset_filename: /Users/mjwen/Packages/camp_analysis/dataset/3BPA/3BPA/val_300K.json
  #  valset_filename: /Users/mjwen/Packages/camp_analysis/dataset/3BPA/3BPA/val_300K.json
  #  testset_filename: /Users/mjwen/Packages/camp_analysis/dataset/3BPA/3BPA/val_300K.json
  #
  #  trainset_filename: /Users/mjwen/Packages/camp_analysis/dataset/bilayer_graphene/bilayer_graphene_small.json
  #  valset_filename: /Users/mjwen/Packages/camp_analysis/dataset/bilayer_graphene/bilayer_graphene_small.json
  #  testset_filename: /Users/mjwen/Packages/camp_analysis/dataset/bilayer_graphene/bilayer_graphene_small.json
  r_cut: 5.0
  train_batch_size: 4
  val_batch_size: 20
  test_batch_size: 20

model:
  atomic_moment_mode: vanilla # architecture of atomic moment, `vanilla`,  `variant1` or `variant2`
  tp_path_mode: full # options: `full`, `lite`, `camp`

  F: 8 # number of channels
  num_layers: 2 # number of layers
  num_average_neigh: auto # average number of neighbors (float), if `auto` determined automatically from training set

  # angular
  max_L: 3 # max rank of natural tensor
  max_degree: 3 # max correlation degree


  # radial
  radial_mlp_hidden_layers: 2
  max_chebyshev_degree: 8 # max degree of Chebyshev polynomial for the radial part

  #
  layer_norm: false
  activation: null
  last_layer_activation: false # has to be `false` if `activation` is `null`
  residual: true

  # optional layers
  use_linear_channel_input: false
  use_linear_channel_hyper: false
  use_linear_channel_residual: true

  # output
  output_mlp_hidden_layers: 2

loss:
  energy_ratio: 1.0
  forces_ratio: 1.0
  normalize: true # normalize energy by number of atoms

metrics:
  type: mae
  normalize: true # normalize energy by number of atoms
  validation_start_epoch: 0 # start calculating metrics at this epoch

optimizer:
  class_path: torch.optim.Adam
  init_args:
    amsgrad: true
    lr: 0.01
    weight_decay: 0.0

lr_scheduler:
  monitor: val/mae_f
  class_path: torch.optim.lr_scheduler.ReduceLROnPlateau
  init_args:
    mode: min
    factor: 0.8
    patience: 100
    verbose: true
#lr_scheduler:
#  class_path: carten.model.pl.scheduler.LinearWarmupCosineAnnealingWarmRestarts
#  init_args:
#    start_factor: 0.01
#    warmup_epochs: 10
#    T_0: 100

ema: # exponential moving average, https://github.com/lucidrains/ema-pytorch
  beta: 0.99
  update_after_step: 100
  update_every: 10
  power: 0.75
  include_online_model: false

trainer:
  max_epochs: 2
  accelerator: cpu
  num_nodes: 1
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  detect_anomaly: false
  inference_mode: false # Enable calculation of gradients (forces) in val/test step
  gradient_clip_val: 100.0

  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      project: carten_proj

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelSummary
      init_args:
        max_depth: -1
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: null
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_ema/mae_e
        mode: min
        save_top_k: 3
        verbose: false
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_ema/mae_e
        mode: min
        patience: 200
        verbose: true
#    - class_path: lightning.pytorch.callbacks.StochasticWeightAveraging
#      init_args:
#        swa_lrs: 0.001
#        swa_epoch_start: 0.8

wandb_base_url: https://api.bandw.top  # https://api.wandb-cn.top
